##
# Copyright (c) Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
#  # Class added in container in index.php
#  config:
#    class: \Eureka\Component\Config\Config
##

all:

  error:
    class: \Eureka\Kernel\Http\Error\ErrorHandler

  router:
    class: \Eureka\Component\Routing\Router
    params:
      - "%app.routing%"

  twig.loader:
    class: \Twig_Loader_Filesystem

  # Uncomment following lines to activate connection service
#  database.connection.common:
#    class: \Eureka\Component\Database\Connection
#    params:
#     - "%app.database.common.dsn%"
#     - "%app.database.common.user%"
#      - "%app.database.common.pass%"
#      - "%app.database.common.options%"
#      - 'common'
