##
# Copyright (c) Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

# File to configure twig layout / templates

all:
  theme:
    layout: '%app.app.root%/vendor/eureka/theme-bootstrap-bootswatch/resources/layout'
    template: '%app.app.root%/vendor/eureka/theme-bootstrap-bootswatch/resources/template'

  debug: false
  cache:
    enabled: true
    path: '%app.cache.path%/twig'


dev:
  debug: true
  cache:
    enabled: false
