##
# Copyright (c) Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

all:
  memcached:
    enabled: true
    driver: 'memcached'
    server:
      host: '127.0.0.1'
      port: 11211

dev:
  memcached:
    enabled: false

prod:
