##
# Copyright (c) Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

# Databases config file

all:

  # Common config database
  common:
    name:   'common'
    engine: 'Connection'
    dsn:    'mysql:dbname=mydatabase;host=localhost'
    options:
      Connection::MYSQL_ATTR_INIT_COMMAND: "SET NAMES 'UTF8'"

dev:
  common:
    user:   'web'
    pass:   'webpass'

preprod:
  common:
    user:   ''
    pass:   ''

prod:
  common:
    user:   ''
    pass:   ''
