##
# Copyright (c) Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

# Middleware config

all:

  Error:
    class: \Eureka\Kernel\Http\Middleware\ErrorMiddleware
    services: []

  Router:
    class: \Eureka\Kernel\Http\Middleware\RouterMiddleware
    services: []

  Controller:
    class: \Eureka\Kernel\Http\Middleware\ControllerMiddleware
    services: []
